export const WIRES: [string, string][] = [
    ["reference", "compress_config"],
    ["compress_config", "compress"],
    ["compress", "extracting"],
    ["extracting", "split"],
    ["extracting", "script_analysis"],
    ["extracting", "audio_analysis"],
    ["extracting", "visual_analysis"],
    ["script_analysis", "plan"],
    ["audio_analysis", "plan"],
    ["visual_analysis", "plan"],
    ["plan", "plan_generate"],
    ["plan", "render"],
    ["plan", "version_preview"],
];
